### ISSUE TITLE
Retaining objects when call clSetKernelArg

### ISSUE THREAD

**Issue by alan-baker** [kpet/clvk#157]
clSetKernelArg currently retains arguments by virtue of maintaining a refcounted_holder for each arg. This seems to go against the guidance in the API documentation:
>A kernel object does not update the reference count for objects such as memory, sampler objects specified as argument values by clSetKernelArg. Users may not rely on a kernel object to retain objects specified as argument values to the kernel.

This leads to a situation where the kernel argument must be reset or the kernel must be released in order to full release the memory for buffers and samplers. This recently resulted in a device crash for some tests I was running (due to OOM).

It seems it would be better to retain the memory objects and samplers attached as arguments when the kernel is enqueued and released when that kernel instance completes. To do this, `kernel_argument_values` should only maintain a pointer to the refcounted object instead of a refcounted_holder.

@kpet, any thoughts about the suggested approach?

**Comment by kpet** [comment]
The spec also says:

>Implementations may also modify the reference count, e.g. to track attached objects or to ensure correct operation of in-progress or scheduled activities. The object becomes inaccessible to host code when the number of release operations performed matches the number of retain
operations plus the allocation of the object. At this point the reference count may be zero but
this is not guaranteed.

which seems to leave the door open for implementations to refcount objects anywhere. Since the spec explicitly calls out argument setting as an exception (and has been doing so for many years) I think we should probably consider the current code broken. Assuming that, I agree the refcounting should be done by the kernel instance. More specifically this means that `cvk_command_kernel` should probably have the holders and `kernel_argument_values` simple pointers. This means that we can no longer transfer all argument values by just moving a `kernel_argument_values`. We may want to split `kernel_argument_values` or just accept that both the arguments object and the command will have a pointer to the refcounted kernel arguments.

We should definitely write a CTS test for this. I'm thinking of something along the lines of:

- create a memory object
- set a destructor callback on the memory object
- create a kernel that takes a memory object argument
- set a memory object as argument
- release the memory object
- wait for the callback to fire

In theory, the spec doesn't guarantee that this should work but given we have `test_mem_object_destructor_callback_single` in the CTS, I'm confident this will work on conformant implementations.

We may also want to change the spec to use stronger language. I'm thinking:
>A kernel object **MUST** not update the reference count for objects such as memory, sampler objects specified as argument values by clSetKernelArg.

**Comment by alan-baker** [comment]
CTS addition: https://github.com/KhronosGroup/OpenCL-CTS/pull/665
